# Concat and clean data

In [1]:
import pandas as pd
import os
import sys

# Add project path to os.path
current_path = os.path.abspath('.')
project_name = 'California_Wild_Fire_Prediction'
project_path = os.path.join(current_path.split(project_name)[0], project_name)
print(project_path)
sys.path.append(project_path)

/Users/shawn/Documents/sjsu/2025-1/ML_CMPE257/California_Wild_Fire_Prediction

## Concat data

### fire data + non fire data

In [2]:
# wild fire + non-wild fire
fire_df = pd.read_csv(os.path.join(project_path, 'data', 'calfire_cimis_data', 'finalized', 'calfire_cimis_completed_rows.csv'))
non_fire_df = pd.read_csv(os.path.join(project_path, 'data', 'calfire_cimis_non_wildfire_data', 'finalized', 'cleaned_non_wildfire_dates.csv'))

fire_df_col = set(fire_df.columns)
non_fire_df_col = set(non_fire_df.columns)

print(f"same columns = {sorted(fire_df_col & non_fire_df_col)}")
print(f"Only in fire_df = {sorted(fire_df_col.difference(non_fire_df_col))}")
print(f"Only in non_fire_df = {sorted(non_fire_df_col.difference(fire_df_col))}")

same columns = ['DayAirTmpAvg01', 'DayAirTmpAvg02', 'DayAirTmpAvg03', 'DayAirTmpAvg04', 'DayAirTmpAvg05', 'DayAirTmpAvg06', 'DayAirTmpAvg07', 'DayAirTmpAvg08', 'DayAirTmpAvg09', 'DayAirTmpAvg10', 'DayAirTmpAvg11', 'DayAirTmpAvg12', 'DayAirTmpAvg13', 'DayAirTmpAvg14', 'DayPrecip01', 'DayPrecip02', 'DayPrecip03', 'DayPrecip04', 'DayPrecip05', 'DayPrecip06', 'DayPrecip07', 'DayPrecip08', 'DayPrecip09', 'DayPrecip10', 'DayPrecip11', 'DayPrecip12', 'DayPrecip13', 'DayPrecip14', 'DayRelHumAvg01', 'DayRelHumAvg02', 'DayRelHumAvg03', 'DayRelHumAvg04', 'DayRelHumAvg05', 'DayRelHumAvg06', 'DayRelHumAvg07', 'DayRelHumAvg08', 'DayRelHumAvg09', 'DayRelHumAvg10', 'DayRelHumAvg11', 'DayRelHumAvg12', 'DayRelHumAvg13', 'DayRelHumAvg14', 'DaySoilTmpAvg01', 'DaySoilTmpAvg02', 'DaySoilTmpAvg03', 'DaySoilTmpAvg04', 'DaySoilTmpAvg05', 'DaySoilTmpAvg06', 'DaySoilTmpAvg07', 'DaySoilTmpAvg08', 'DaySoilTmpAvg09', 'DaySoilTmpAvg10', 'DaySoilTmpAvg11', 'DaySoilTmpAvg12', 'DaySoilTmpAvg13', 'DaySoilTmpAvg14', 'DayWindSpdAvg01', 'DayWindSpdAvg02', 'DayWindSpdAvg03', 'DayWindSpdAvg04', 'DayWindSpdAvg05', 'DayWindSpdAvg06', 'DayWindSpdAvg07', 'DayWindSpdAvg08', 'DayWindSpdAvg09', 'DayWindSpdAvg10', 'DayWindSpdAvg11', 'DayWindSpdAvg12', 'DayWindSpdAvg13', 'DayWindSpdAvg14']
Only in fire_df = ['incident_acres_burned', 'incident_date_created', 'incident_date_last_update', 'incident_dateonly_created', 'incident_id', 'incident_latitude', 'incident_longitude', 'incident_name']
Only in non_fire_df = ['DayAirTmpAvg', 'DayPrecip', 'DayRelHumAvg', 'DaySoilTmpAvg', 'DayWindSpdAvg', 'county', 'date', 'latitude', 'longitude']

Columns should be changed

- date = fire_df.incident_date_created, non_fire_df.date
- lat = fire_df.incident_latitude, latitude
- lng = fire_df.incident_longitude, longitude
- acres_burned = fire_df.incident_acres_burned, 0

In [3]:
fire_df_processed = fire_df[sorted(fire_df_col & non_fire_df_col)].copy()
fire_df_processed.loc[:, 'date'] = fire_df.incident_date_created
fire_df_processed.loc[:, 'lat'] = fire_df.incident_latitude
fire_df_processed.loc[:, 'lng'] = fire_df.incident_longitude
fire_df_processed.loc[:, 'acres_burned'] = fire_df.incident_acres_burned
fire_df_processed.loc[:, 'is_fire'] = [1] * len(fire_df_processed)
fire_df_processed.head(3)

,DayAirTmpAvg01,DayAirTmpAvg02,DayAirTmpAvg03,DayAirTmpAvg04,DayAirTmpAvg05,DayAirTmpAvg06,DayAirTmpAvg07,DayAirTmpAvg08,DayAirTmpAvg09,DayAirTmpAvg10,...,DayWindSpdAvg10,DayWindSpdAvg11,DayWindSpdAvg12,DayWindSpdAvg13,DayWindSpdAvg14,date,lat,lng,acres_burned,is_fire
0,9.6,9.3,7.6,4.6,5.5,9.2,12.3,14.5,10.6,10.0,...,1.0,0.9,1.1,0.8,2.8,2017-10-31T11:22:00Z,40.774000,-122.309000,37.0,1
1,22.3,22.0,25.4,25.8,22.8,22.8,19.7,20.9,22.7,23.6,...,2.1,2.3,2.4,3.2,2.0,2022-04-30T20:33:00Z,33.510716,-115.916687,15.0,1
2,20.2,15.5,15.3,17.2,16.8,18.3,17.1,19.6,20.0,20.1,...,3.2,4.0,2.5,4.0,4.2,2013-06-04T15:42:00Z,37.037760,-121.006939,124.0,1

In [4]:
non_fire_df_processed = non_fire_df[sorted(fire_df_col & non_fire_df_col)].copy()
non_fire_df_processed.loc[:, 'date'] = non_fire_df.date
non_fire_df_processed.loc[:, 'lat'] = non_fire_df.latitude
non_fire_df_processed.loc[:, 'lng'] = non_fire_df.longitude
non_fire_df_processed.loc[:, 'acres_burned'] = [0] * len(non_fire_df_processed)
non_fire_df_processed.loc[:, 'is_fire'] = [0] * len(non_fire_df_processed)
non_fire_df_processed.head(3)

,DayAirTmpAvg01,DayAirTmpAvg02,DayAirTmpAvg03,DayAirTmpAvg04,DayAirTmpAvg05,DayAirTmpAvg06,DayAirTmpAvg07,DayAirTmpAvg08,DayAirTmpAvg09,DayAirTmpAvg10,...,DayWindSpdAvg10,DayWindSpdAvg11,DayWindSpdAvg12,DayWindSpdAvg13,DayWindSpdAvg14,date,lat,lng,acres_burned,is_fire
0,25.8,19.7,20.7,22.4,23.4,24.8,26.3,22.8,18.9,19.4,...,3.5,5.0,4.6,3.7,2.1,2022-06-02,37.471329,-121.23737,0,0
1,25.5,25.3,24.5,21.9,27.5,28.4,31.0,23.9,24.1,24.6,...,1.2,1.4,1.8,1.3,1.1,2022-08-12,39.325600,-121.36860,0,0
2,11.0,14.5,14.4,13.1,11.4,11.3,8.8,10.0,9.3,6.3,...,1.7,1.2,1.1,1.1,1.4,2010-01-27,33.932440,-117.03459,0,0

In [16]:
total_fire_df = pd.concat([non_fire_df_processed, fire_df_processed])
total_fire_df.reset_index()
print(f"Total data rows are {len(total_fire_df)}")
print(f"Total data cols are {len(total_fire_df.columns)}")

Total data rows are 4198
Total data cols are 75

### fire data + landfire data

In [6]:
from src.dataset_script.add_landfire_data import add_landfire_data
print(add_landfire_data.__doc__)

/Users/shawn/Documents/sjsu/2025-1/ML_CMPE257/California_Wild_Fire_Prediction

    Add new landfire columns (features) to existing fire data.

    Landfire data is used located in data/landfire_data/processed/

    Params:
    - fire_df: existing fire data path

In [ ]:
# takes about 10 minutes to execute this code.

total_fire_df_with_landfire = add_landfire_data(total_fire_df)

In [25]:
total_fire_df_with_landfire.reset_index(inplace=False)
total_fire_df_with_landfire.head(3)

,index,DayAirTmpAvg01,DayAirTmpAvg02,DayAirTmpAvg03,DayAirTmpAvg04,DayAirTmpAvg05,DayAirTmpAvg06,DayAirTmpAvg07,DayAirTmpAvg08,DayAirTmpAvg09,...,CBD_VALUE,cbd_DISTANCE_KM,EVC_VALUE,evc_DISTANCE_KM,FBFM_VALUE,fbfm_DISTANCE_KM,FDIST_VALUE,fdist_DISTANCE_KM,FVC_VALUE,fvc_DISTANCE_KM
0,0,25.8,19.7,20.7,22.4,23.4,24.8,26.3,22.8,18.9,...,1,838.590306,251,838.590306,-9999,838.590306,112,838.590306,125,838.590306
1,1,25.5,25.3,24.5,21.9,27.5,28.4,31.0,23.9,24.1,...,1,1044.446304,251,1044.446304,-9999,1044.446304,112,1044.446304,125,1044.446304
2,2,11.0,14.5,14.4,13.1,11.4,11.3,8.8,10.0,9.3,...,16,519.022245,166,519.022245,-9999,519.022245,112,519.022245,106,519.022245

In [27]:
total_fire_df_with_landfire = total_fire_df_with_landfire.drop(columns = [col for col in total_fire_df_with_landfire.columns if 'KM' in col] + ['index'])
total_fire_df_with_landfire.head(3)

,DayAirTmpAvg01,DayAirTmpAvg02,DayAirTmpAvg03,DayAirTmpAvg04,DayAirTmpAvg05,DayAirTmpAvg06,DayAirTmpAvg07,DayAirTmpAvg08,DayAirTmpAvg09,DayAirTmpAvg10,...,date,lat,lng,acres_burned,is_fire,CBD_VALUE,EVC_VALUE,FBFM_VALUE,FDIST_VALUE,FVC_VALUE
0,25.8,19.7,20.7,22.4,23.4,24.8,26.3,22.8,18.9,19.4,...,2022-06-02,37.471329,-121.23737,0.0,0,1,251,-9999,112,125
1,25.5,25.3,24.5,21.9,27.5,28.4,31.0,23.9,24.1,24.6,...,2022-08-12,39.325600,-121.36860,0.0,0,1,251,-9999,112,125
2,11.0,14.5,14.4,13.1,11.4,11.3,8.8,10.0,9.3,6.3,...,2010-01-27,33.932440,-117.03459,0.0,0,16,166,-9999,112,106

In [28]:
print(f"Total data rows are {len(total_fire_df_with_landfire)}")
print(f"Total data cols are {len(total_fire_df_with_landfire.columns)}")

Total data rows are 4198
Total data cols are 80

### fire data + risk data

@Hashem you can start from here